package com.zeed.paaro.lib.enums;

public enum TransactionStatus {

    PENDING,
    COMPLETED,
    DECLINED,
    PAARO_REFERENCE_ID_GENERATED,
    SUCCESSFULL,
    FAILED,
    WALLET_FUNDING_FAILED,
    CUSTOMER_LOGGED_REQUEST,
    SYSTEM_MAPPED_REQUEST,
    ADMIN_SETTLED,
    CUSTOMER_CONFIRMED,
    CUSTOMER_COMPLAINED,
    CLOSED

}
